name: Deploy to Server to App Engine
'on':
  push:
    branches:
      - main
    paths:
      - "apps/server/**"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci && npm run build:server
      - run: echo "My $APP_ID - $SERVER_URL"
        env:
          APP_ID: ${{ env.APP_ID }}
      - name: Deploy to App Engine
        uses: google-github-actions/deploy-appengine@v0.2.0
        with:
          deliverables: app.yaml
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          promote: false
          version: v1
        env:
          DATABASE_URI: ${{ env.DATABASE_URI }}
          APP_ID: ${{ env.APP_ID }}
          MASTER_KEY: ${{ env.MASTER_KEY }}
          SERVER_URL: ${{ env.SERVER_URL }}

